# Generated by Django 5.1.1 on 2024-11-01 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0001_initial'),
        ('Properties', '0003_propertymodel_floor_number_propertymodel_house_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Properties.propertymodel', verbose_name='ملک مرتبط'),
        ),
    ]
