# Generated by Django 5.1.1 on 2024-09-28 16:01

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس')),
                ('area', models.FloatField(verbose_name='مساحت')),
                ('property_type', models.CharField(choices=[('for_rent', 'اجاره'), ('for_sale', 'فروش'), ('for_mortage', 'رهن')], max_length=20, verbose_name='نوع آگهی')),
                ('date_posted', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='اضافه شده در تاریخ')),
                ('image', models.ImageField(upload_to='files/images', verbose_name='تصویر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ملک',
                'verbose_name_plural': 'املاک',
            },
        ),
    ]
