# Generated by Django 5.1.1 on 2024-10-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0002_propertymodel_amenities_propertymodel_bath_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره طبقه'),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='house_type',
            field=models.CharField(choices=[('آپارتمانی', 'آپارتمانی'), ('ویلایی', 'ویلایی')], default='آپارتمانی', max_length=20, verbose_name='نوع خانه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='description',
            field=models.TextField(max_length=500, verbose_name='توضیحات'),
        ),
    ]
